name: Building docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build-essential and make
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ca-certificates curl libffi-dev libgdbm-dev libncurses5-dev libnss3-dev libreadline-dev libssl-dev make time wget zlib1g-dev
    
    - name: Install PyTorch
      run: |
        python -m pip install --upgrade pip
        python -m pip install torch --index-url https://download.pytorch.org/whl/cpu --no-cache-dir

    - name: Install dependencies from pyproject.toml
      run: |
        python -m pip install .[dev,docs]
    
    - name: Cache datasets
      id: cache-datasets
      uses: actions/cache@v3
      with:
        path: ~/.cache/trajdl
        key: trajdl-cache-datasets

    - name: Test with pytest
      run: |
        autoflake -j 0 --remove-all-unused-imports --in-place --recursive --ignore-init-module-imports .
        isort -j -1 .
        black .
        pytest -s

    - name: Build docs
      run: |
        cd docs && make -j 4 html && cd ..

    - name: Get branch name
      id: branch-name
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

    - name: Checkout documentation repository
      uses: actions/checkout@v3
      with:
        repository: Spatial-Temporal-Data-Mining/TrajDL-docs
        token: ${{ secrets.PAT_FOR_DOCS }}
        path: docs-repo
        fetch-depth: 0  # 获取所有分支信息

    - name: Deploy to documentation repository
      run: |
        cd docs-repo
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
        git checkout -b ${{ steps.branch-name.outputs.branch }} || git checkout ${{ steps.branch-name.outputs.branch }}

        # 复制文档
        rm -rf *  # 清空当前分支内容
        cp -r ../docs/build/html/ .
        cp ../.readthedocs.yaml .
        
        # 提交更改
        git add .
        git commit -m "Update documentation from source repository" || echo "No changes to commit"
        git push origin ${{ steps.branch-name.outputs.branch }}
